In [2]:
import pandas as pd
tips = pd.read_csv("tips.csv")

In [3]:
# Drop missing values
cleaned = tips.dropna()

In [4]:
# Melt tips by gender and time
melted = pd.melt(cleaned, id_vars=['sex', 'time'], value_vars=['total_bill', 'tip'])
melted.head()

      sex    time    variable  value
0  Female  Dinner  total_bill  16.99
1    Male  Dinner  total_bill  10.34
2    Male  Dinner  total_bill  21.01
3    Male  Dinner  total_bill  23.68
4  Female  Dinner  total_bill  24.59

In [5]:
# Group by time and variable
grouped = melted.groupby(['time', 'variable'])['value'].mean()
grouped.head()

time    variable
Dinner  tip            3.102670
        total_bill    20.797159
Lunch   tip            2.728088
        total_bill    17.168676
Name: value, dtype: float64